#!/usr/bin/env node
/* Turn the design tables into the modules the game imports.
 *
 *   tools/orbital-trader/design/tuning.json     the sky: bodies, rails, spheres of influence
 *   tools/orbital-trader/design/economy.json    goods, ports, prices, upgrades, formulas
 *   tools/orbital-trader/design/narrative.json  every line of in-world text
 *   tools/orbital-trader/design/quests.json     every errand, in one standard shape
 *   tools/orbital-trader/design/dialog.json     what the crew say, and where
 *
 * become public/orbital-trader/data/{world,economy,text,quests,dialog}.js, each
 * a single `export const` of the same object. The game never fetches JSON: a
 * module is cacheable, importable by the tests under Node, and cannot 404 into
 * a page that draws nothing. The JSON is what a person edits; this is what
 * ships.
 *
 * The quest and dialog tables are checked on the way through — not for taste,
 * which is not a machine's business, but for the things a typo breaks quietly:
 * a missing field, a type nothing handles, a port or a good that does not
 * exist, two records sharing an id. A table with a standard shape is only
 * standard if something insists.
 *
 * Usage: node tools/orbital-trader/build-content.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..', '..');
const src = join(here, 'design');
const out = join(root, 'public', 'orbital-trader', 'data');

const read = name => JSON.parse(readFileSync(join(src, name), 'utf8'));

function emit(file, name, value, note){
  const body = `/* GENERATED by tools/orbital-trader/build-content.mjs from tools/orbital-trader/design/${note}.\n * Do not edit: change the JSON and run the build script. */\nexport const ${name} = ${JSON.stringify(value, null, 1)};\n`;
  writeFileSync(join(out, file), body);
  console.log(`wrote public/orbital-trader/data/${file} (${(body.length / 1024).toFixed(1)} KB)`);
}

const tuning = read('tuning.json');
const economy = read('economy.json');
const narrative = read('narrative.json');
const questbook = read('quests.json');
const dialogue = read('dialog.json');
const eventbook = read('events.json');

/* ------------------------------------------------------------- checking */

const problems = [];
const need = (ok, where, what) => { if(!ok) problems.push(`${where}: ${what}`); };

const portIds = new Set(Object.keys(economy.ports));
const goodIds = new Set(economy.goods.map(g => g.id));
const berths = new Set((narrative.crew?.roles ?? []).map(r => r.id));
const speakers = new Set(['captain', ...berths]);
const peoples = new Set(['emberkin', 'otter', 'cat', 'frog']);
const QUEST_TYPES = new Set(['retrieval', 'delivery', 'shopping', 'chain', 'message', 'salvage']);
/* Bodies with no mass that a ship can tie up to. They are not in the price
   list — a derelict has no stall — so a salvage job's `wreck` is checked
   against the sky rather than against the ports. */
const wreckIds = new Set(tuning.bodies.filter(b => b.kind === 'wreck' && b.port).map(b => b.id));
/* Somewhere a job can end. Usually a port off the price list; but a weightless
   harbour has no price list at all — a derelict has no stall, and neither does
   a Builder station — so the sky is the authority on those. */
const stopIds = new Set([...portIds, ...tuning.bodies.filter(b => b.port && !b.mu).map(b => b.id)]);
const relicIds = new Set((questbook.relics ?? []).map(r => r.id));

/* The quest format, as quests.json describes it. Everything here is something
 * that would otherwise fail at the far end of a flight, in a save, or not at
 * all — a job whose `to` is a port that was renamed simply stops completing. */
const questIds = new Set();
for(const [i, q] of (questbook.quests ?? []).entries()){
  const at = `quest ${q?.id ?? `#${i}`}`;
  for(const k of ['id', 'title', 'giver', 'type', 'from', 'to', 'blurb', 'taken', 'done']){
    need(typeof q?.[k] === 'string' && q[k].length > 0, at, `${k} is required`);
  }
  need(!questIds.has(q?.id), at, 'two quests share an id');
  questIds.add(q?.id);
  need(QUEST_TYPES.has(q?.type), at, `type ${q?.type} is not one of ${[...QUEST_TYPES].join(', ')}`);
  need(portIds.has(q?.from), at, `from names no port: ${q?.from}`);
  need(stopIds.has(q?.to), at, `to names nowhere a ship can tie up: ${q?.to}`);
  for(const id of q?.stops ?? []) need(portIds.has(id), at, `stops names no port: ${id}`);
  need(q?.type === 'chain' || !q?.stops, at, 'stops belongs to a chain');
  if(q?.type === 'salvage'){
    need(wreckIds.has(q?.wreck), at, `wreck names no derelict in the sky: ${q?.wreck}`);
    need((q?.goods ?? []).length > 0, at, 'a salvage with nothing aboard is a trip for nothing');
    need(typeof q?.aboard === 'string' && q.aboard.length > 0, at, 'aboard is required: it is all there is to read at a wreck');
  }else{
    need(!q?.wreck, at, 'only a salvage names a wreck');
    need(!q?.aboard, at, 'only a salvage has an aboard');
  }
  need(Array.isArray(q?.goods), at, 'goods is required, empty if there are none');
  for(const g of q?.goods ?? []){
    need(goodIds.has(g?.good), at, `wants a good that does not exist: ${g?.good}`);
    need(Number.isInteger(g?.qty) && g.qty > 0, at, `${g?.good}: qty must be a whole number above zero`);
  }
  need(q?.type !== 'message' || !(q?.goods ?? []).length, at, 'a message carries nothing');
  /* A job usually pays in coin. Two of them pay in the thing itself — a person
     for a berth, or a relic — and for those the fee is allowed to be nothing,
     because the point of the trip is what you are handed at the end of it. */
  const paysInKind = !!q?.crew || !!q?.relic || !!q?.ends;
  need(Number.isInteger(q?.pay) && (q.pay > 0 || (paysInKind && q.pay === 0)), at,
    paysInKind ? 'pay must be a whole number, and may be zero when the job pays in kind'
               : 'pay must be a whole number above zero');
  if(q?.relic) need(relicIds.has(q.relic), at, `relic names nothing in the relics block: ${q.relic}`);
  for(const id of q?.requires?.relics ?? []) need(relicIds.has(id), at, `requires a relic that does not exist: ${id}`);
  for(const people of Object.keys(q?.requires?.questsFor ?? {})) need(peoples.has(people), at, `requires jobs for nobody: ${people}`);
  need(peoples.has(q?.rep), at, `rep names no people: ${q?.rep}`);
  if(q?.crew) need(berths.has(q.crew), at, `crew names no berth: ${q.crew}`);
  for(const st of q?.steps ?? []) need(st?.id && st?.text, at, 'a written step needs an id and text');
}

/* The dialog format, as dialog.json describes it. */
const exchangeIds = new Set();
for(const [i, x] of (dialogue.exchanges ?? []).entries()){
  const at = `exchange ${x?.id ?? `#${i}`}`;
  need(typeof x?.id === 'string' && x.id.length > 0, at, 'id is required');
  need(!exchangeIds.has(x?.id), at, 'two exchanges share an id');
  exchangeIds.add(x?.id);
  need(x?.at === '*' || portIds.has(x?.at), at, `at names no port: ${x?.at}`);
  need(speakers.has(x?.who), at, `who names nobody aboard: ${x?.who}`);
  for(const id of x?.needs ?? []) need(berths.has(id), at, `needs names no berth: ${id}`);
  need(Array.isArray(x?.lines) && x.lines.length > 0, at, 'an exchange with no lines says nothing');
  for(const l of x?.lines ?? []){
    need(speakers.has(l?.who), at, `a line is spoken by nobody aboard: ${l?.who}`);
    need(typeof l?.say === 'string' && l.say.length > 0, at, `${l?.who} has nothing to say`);
  }
  /* Somebody has to be there to say their half of it. The speaker counts as
     needed whether or not `needs` bothers to mention them. */
  const mustBeAboard = new Set([x?.who, ...(x?.needs ?? []), ...(x?.lines ?? []).map(l => l?.who)]);
  mustBeAboard.delete('captain');
  for(const id of mustBeAboard) need(berths.has(id), at, `nobody fills the berth ${id}`);
  /* What is said when one of them is not there. A fallback may only name a
     berth the exchange actually leans on — the speaker's own is not one, they
     are the one pressing — and may only be spoken by the two people certain
     to be aboard, or it would need a fallback of its own. */
  if(x?.without !== undefined){
    need(x.without && typeof x.without === 'object' && !Array.isArray(x.without), at, '`without` is a map of berth to lines');
    const leansOn = new Set(mustBeAboard); leansOn.delete(x?.who);
    for(const [berth, lines] of Object.entries(x.without ?? {})){
      need(leansOn.has(berth), at, `without: the exchange does not need the ${berth}`);
      need(Array.isArray(lines) && lines.length > 0, at, `without ${berth}: nothing is said instead`);
      for(const l of lines ?? []){
        need(l?.who === x?.who || l?.who === 'captain', at, `without ${berth}: only ${x?.who} and the captain are certain to be there to say it, not ${l?.who}`);
        need(typeof l?.say === 'string' && l.say.length > 0, at, `without ${berth}: ${l?.who} has nothing to say`);
      }
    }
  }
}

/* The event format, as events.json describes it. */
{
  const regions = new Set(['inner', 'home', 'belt', 'outer', 'deep']);
  const categories = new Set(economy.goods.map(g => g.category));
  const kinds = id => goodIds.has(id) || categories.has(id);
  const keys = new Set(['heatShield', 'tempControl', 'gravSensors', 'cryoCooling', 'astrolabe']);
  const repNames = new Set([...peoples, 'here']);
  const chance = eventbook.rules?.chance;
  need(typeof chance === 'number' && chance >= 0 && chance <= 1, 'events rules', `chance must be 0..1, not ${chance}`);
  const eventIds = new Set();
  const checkEffects = (fx, at) => {
    if(fx === undefined) return;
    need(fx && typeof fx === 'object' && !Array.isArray(fx), at, 'effects is a map');
    for(const k of Object.keys(fx ?? {})) need(['money', 'dv', 'rep', 'cargo', 'hull', 'debt'].includes(k), at, `unknown effect: ${k}`);
    const m = fx?.money;
    if(m !== undefined && typeof m !== 'number'){
      need(typeof m?.fraction === 'number' && ['purse', 'cargo', 'contraband'].includes(m?.of), at, 'money is a number or { fraction, of, cap }');
    }
    if(fx?.dv !== undefined) need(typeof fx.dv === 'number', at, 'dv is a number of km/s');
    for(const [who, d] of Object.entries(fx?.rep ?? {})) need(repNames.has(who) && typeof d === 'number', at, `rep names nobody: ${who}`);
    const c = fx?.cargo;
    if(c !== undefined){
      const ways = ['take', 'takeCold', 'give'].filter(k => c?.[k] !== undefined);
      need(ways.length === 1, at, 'cargo does exactly one of take, takeCold, give');
      if(c?.take !== undefined) need(kinds(c.take), at, `cargo takes something that does not exist: ${c.take}`);
      if(c?.give !== undefined) need(goodIds.has(c.give) && Number.isInteger(c.qty) && c.qty > 0, at, `cargo gives something that does not exist, or none of it: ${c.give}`);
      if(c?.takeCold !== undefined) need(typeof c.takeCold === 'number' && c.takeCold > 0 && c.takeCold <= 1, at, 'takeCold is a fraction');
    }
    if(fx?.hull !== undefined) need(Number.isInteger(fx.hull) && fx.hull !== 0, at, 'hull is a whole number of grades');
    const d = fx?.debt;
    if(d !== undefined) need((typeof d?.pay === 'number') !== (typeof d?.add === 'number'), at, 'debt is { pay } or { add }');
  };
  for(const [i, ev] of (eventbook.events ?? []).entries()){
    const at = `event ${ev?.id ?? `#${i}`}`;
    need(typeof ev?.id === 'string' && /^[a-z0-9-]+$/.test(ev.id), at, 'id is required, lower case, no spaces');
    need(!eventIds.has(ev?.id), at, 'two events share an id');
    eventIds.add(ev?.id);
    for(const k of ['title', 'text']) need(typeof ev?.[k] === 'string' && ev[k].length > 0, at, `${k} is required`);
    if(ev?.weight !== undefined) need(typeof ev.weight === 'number' && ev.weight > 0, at, 'weight is a number above zero');
    const w = ev?.when ?? {};
    for(const k of Object.keys(w)) need(['regions', 'carrying', 'notCarrying', 'coldCargo', 'debt', 'hull'].includes(k), at, `unknown condition: ${k}`);
    for(const r of w.regions ?? []) need(regions.has(r), at, `no such region: ${r}`);
    for(const g of [...(w.carrying ?? []), ...(w.notCarrying ?? [])]) need(kinds(g), at, `carrying names nothing in the goods table: ${g}`);
    need(Array.isArray(ev?.choices) && ev.choices.length > 0, at, 'an event with no choices is not an event');
    /* A card every button on which is greyed is a card that cannot be closed. */
    need((ev?.choices ?? []).some(ch => !ch?.requires || !Object.keys(ch.requires).length), at, 'every choice needs something; a ship with nothing could not answer');
    for(const [j, ch] of (ev?.choices ?? []).entries()){
      const where = `${at} choice ${j + 1}`;
      need(typeof ch?.label === 'string' && ch.label.length > 0, where, 'label is required');
      for(const [k, v] of Object.entries(ch?.requires ?? {})) need(['dv', 'money', 'holdUnits'].includes(k) && typeof v === 'number' && v > 0, where, `requires: ${k} is not a thing a choice can need`);
      if(ch?.outcomes !== undefined){
        need(Array.isArray(ch.outcomes) && ch.outcomes.length > 0, where, 'outcomes is a list');
        need(ch.text === undefined && ch.effects === undefined, where, 'a choice has outcomes, or text and effects, not both');
        need((ch.outcomes ?? []).some(o => !o?.when), where, 'every outcome is conditional, so sometimes nothing can happen');
        for(const o of ch.outcomes ?? []){
          need(typeof o?.text === 'string' && o.text.length > 0, where, 'an outcome with no text');
          if(o?.weight !== undefined) need(typeof o.weight === 'number' && o.weight > 0, where, 'an outcome weight above zero');
          if(o?.when !== undefined) need(keys.has(o.when?.key), where, `an outcome waits on a key that does not exist: ${o.when?.key}`);
          checkEffects(o?.effects, where);
        }
      }else{
        need(typeof ch?.text === 'string' && ch.text.length > 0, where, 'text is required unless there are outcomes');
        checkEffects(ch?.effects, where);
      }
    }
  }
}

if(problems.length){
  console.error(`${problems.length} problem${problems.length === 1 ? '' : 's'} in the design tables:`);
  for(const p of problems) console.error(`  ${p}`);
  process.exit(1);
}

/* -------------------------------------------------------------- writing */

// The simulator's private assumptions are not content.
delete economy.sim;
for(const p of Object.values(economy.ports)) delete p.notes;
/* One ending, and it is the only job allowed to pay in nothing at all. */
{
  const ends = (questbook.quests ?? []).filter(q => q.ends);
  need(ends.length === 1, 'the line', `${ends.length} jobs say they end it`);
}

/* And the relics themselves. */
const seenRelics = new Set();
for(const [i, r] of (questbook.relics ?? []).entries()){
  const at = `relic ${r?.id ?? `#${i}`}`;
  for(const k of ['id', 'name', 'blurb']) need(typeof r?.[k] === 'string' && r[k].length > 0, at, `${k} is required`);
  need(!seenRelics.has(r?.id), at, 'two relics share an id');
  seenRelics.add(r?.id);
  need((questbook.quests ?? []).some(q => q.relic === r?.id), at, 'nothing in the line grants it');
}

// The format is written down for whoever edits the table, not for the game.
delete questbook.notes;
delete dialogue.notes;
delete eventbook.notes;

emit('world.js', 'TUNING', tuning, 'tuning.json');
emit('economy.js', 'ECONOMY', economy, 'economy.json');
emit('text.js', 'NARRATIVE', narrative, 'narrative.json');
emit('quests.js', 'QUESTBOOK', questbook, 'quests.json');
emit('dialog.js', 'DIALOGUE', dialogue, 'dialog.json');
emit('events.js', 'EVENTBOOK', eventbook, 'events.json');
