#!/usr/bin/env node
/* Turn the design tables into the modules the game imports.
 *
 *   tools/orbital-trader/design/tuning.json     the sky: bodies, rails, spheres of influence
 *   tools/orbital-trader/design/economy.json    goods, ports, prices, upgrades, formulas
 *   tools/orbital-trader/design/narrative.json  every line of in-world text
 *
 * become public/orbital-trader/data/{world,economy,text}.js, each a single
 * `export const` of the same object. The game never fetches JSON: a module is
 * cacheable, importable by the tests under Node, and cannot 404 into a page
 * that draws nothing. The JSON is what a person edits; this is what ships.
 *
 * Usage: node tools/orbital-trader/build-content.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..', '..');
const src = join(here, 'design');
const out = join(root, 'public', 'orbital-trader', 'data');

const read = name => JSON.parse(readFileSync(join(src, name), 'utf8'));

function emit(file, name, value, note){
  const body = `/* GENERATED by tools/orbital-trader/build-content.mjs from tools/orbital-trader/design/${note}.\n * Do not edit: change the JSON and run the build script. */\nexport const ${name} = ${JSON.stringify(value, null, 1)};\n`;
  writeFileSync(join(out, file), body);
  console.log(`wrote public/orbital-trader/data/${file} (${(body.length / 1024).toFixed(1)} KB)`);
}

const tuning = read('tuning.json');
const economy = read('economy.json');
const narrative = read('narrative.json');

// The simulator's private assumptions are not content.
delete economy.sim;
for(const p of Object.values(economy.ports)) delete p.notes;

emit('world.js', 'TUNING', tuning, 'tuning.json');
emit('economy.js', 'ECONOMY', economy, 'economy.json');
emit('text.js', 'NARRATIVE', narrative, 'narrative.json');
